### ISSUE TITLE
My Application Home Page is not Loading..Please help me sort it out!!

### ISSUE THREAD

**Issue by ashikmhussain** [SenseNet/awesome-sensenet#8]
Hi I have Installed Sensenet 7.0 in my simple MVC Application and completed all the procedures you mentioned in the community with out any build errors but when I run my Application, my window looked like this.
![senseneterorr](https://user-images.githubusercontent.com/38417201/38870387-46c5f3fe-426b-11e8-9bd9-978c8f30e78b.JPG)

When I tried to put break point on Global.asax the Cursor point Came at line **"base.Application_Start(sender, e, application);"** and vanishes. Neither its coming back nor its showing any exception.
**This my global.asax file code:** 
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;
using System.Web.Routing;

namespace SENSENT7oo
{
    public class MvcApplication : SenseNet.Portal.SenseNetGlobal  
    {
        protected override void Application_Start(object sender, EventArgs e, HttpApplication application)
        {
            base.Application_Start(sender, e, application);
    
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }
    }
}


```
I have no idea about what is the issue. Because in the video you provided its perfectly working. Do you have any issues in the later versions of 7.0
![senseneteror2r](https://user-images.githubusercontent.com/38417201/38870308-110b8c10-426b-11e8-9f88-096835e4ca1b.JPG)

**Comment by tusmester** [comment]
It is possible that the following issue caused this (accessing the performance counter API). I'm closing this one, if anybody still encounters the same problem, please open an issue in the main [sensenet repository](https://github.com/SenseNet/sensenet).

* https://github.com/SenseNet/sensenet/issues/411
